version: "3"
services:
  count-service:
    image: jrec/count:0.1
    ports:
      - "8000:8080"
    networks:
      - webnet
  showcount-service:
    image: jrec/showcount:0.1
    ports:
      - "8001:8080"
    networks:
      - webnet
networks:
  webnet:
