version: "3"
services:
  
  db:
    image: postgres
    ports:
     - "5433:5432"
    environment:
     - POSTGRES_PASSWORD=password
     - POSTGRES_USER=postgres
     - POSTGRES_DB=countDb
    networks:
      - webnet
networks:
  webnet:
